apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qpu1kd80a-go
  janus-idp.io/tekton: qpu1kd80a-go
  backstage.io/kubernetes-id: qpu1kd80a-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qpu1kd80a-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
