apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qpu1kd80a-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qpu1kd80a-go 
  name: qpu1kd80a-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qpu1kd80a-go 
